apiVersion: 1

datasources:
  - name: Narration JSON
    type: yesoreyeram-infinity-datasource
    uid: narration-json
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      # Infinity datasource reads JSON from the narration HTTP endpoint
      global_queries: []
